//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poppel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string customer_id { get; set; }
        public string customer_name { get; set; }
        public string customer_surname { get; set; }
        public string customer_telephoneNumber { get; set; }
        public string customer_email { get; set; }
        public Nullable<decimal> customer_credit { get; set; }
        public Nullable<decimal> customer_creditLimit { get; set; }
        public string customer_street { get; set; }
        public string customer_suburb { get; set; }
        public string customer_town { get; set; }
        public string customer_city { get; set; }
        public string customer_zipCode { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
