//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poppel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int delivery_id { get; set; }
        public Nullable<System.DateTime> delivery_startTime { get; set; }
        public Nullable<System.DateTime> delivery_endTime { get; set; }
        public Nullable<int> order_id { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
