//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poppel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string employee_id { get; set; }
        public string employee_name { get; set; }
        public string employee_surname { get; set; }
        public string employee_telephoneNumber { get; set; }
        public string employee_email { get; set; }
        public string employee_street { get; set; }
        public string employee_suburb { get; set; }
        public string employee_town { get; set; }
        public string employee_city { get; set; }
        public string employee_zipCode { get; set; }
        public string employee_password { get; set; }
        public Nullable<decimal> employee_salary { get; set; }
        public string employee_position { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
