//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poppel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStockItem
    {
        public int orderItem_id { get; set; }
        public int stockItem_id { get; set; }
        public Nullable<int> item_quantity { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
        public virtual StockItem StockItem { get; set; }
    }
}
