//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poppel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Deliveries = new HashSet<Delivery>();
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int order_id { get; set; }
        public Nullable<System.DateTime> order_datePlaced { get; set; }
        public string customer_id { get; set; }
        public string employee_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Delivery> Deliveries { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
