//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poppel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public OrderItem()
        {
            this.OrderStockItems = new HashSet<OrderStockItem>();
        }
    
        public int order_id { get; set; }
        public int product_quantity { get; set; }
        public int orderItem_id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<OrderStockItem> OrderStockItems { get; set; }
    }
}
