//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poppel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItem
    {
        public StockItem()
        {
            this.OrderStockItems = new HashSet<OrderStockItem>();
        }
    
        public int stockItem_id { get; set; }
        public Nullable<System.DateTime> stockItem_expityDate { get; set; }
        public string stockItem_rackNumber { get; set; }
        public Nullable<int> stockItem_numberInStock { get; set; }
        public Nullable<int> product_ref { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<OrderStockItem> OrderStockItems { get; set; }
    }
}
